# Generated by Django 5.2.7 on 2026-05-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_position_profile_role_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('junior', 'Младшая группа'), ('teen', 'Подростковая группа'), ('adult', 'Взрослые')], max_length=10, verbose_name='Тип теста')),
                ('score', models.IntegerField(verbose_name='Набранные баллы')),
                ('total_questions', models.IntegerField(verbose_name='Всего вопросов')),
                ('passing_score', models.IntegerField(verbose_name='Проходной балл')),
                ('passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
    ]
