# Generated by Django 5.2.7 on 2026-05-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата проведения урока')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('children_count', models.PositiveIntegerField(verbose_name='Количество детей')),
                ('children_list', models.TextField(help_text='Введите имена детей через запятую или с новой строки', verbose_name='Список детей')),
                ('photo_link', models.URLField(blank=True, help_text='Ссылка на фотоальбом, облачное хранилище или группу в соцсетях', verbose_name='Ссылка на фотоотчёт или группу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчёта')),
                ('certificate_generated', models.BooleanField(default=False, verbose_name='Грамота сгенерирована')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Отчёт об уроке ПДД',
                'verbose_name_plural': 'Отчёты об уроках ПДД',
                'ordering': ['-lesson_date'],
            },
        ),
    ]
