# Generated by Django 5.2.7 on 2026-06-24 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacherlessonreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('junior', 'Младшая группа (8-12)'), ('teen', 'Подростковая группа (12-15)'), ('adult', 'Старшая группа (16-18)')], max_length=10, verbose_name='Тип теста')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('download_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.testresult', verbose_name='Результат теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Сертификаты')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-generated_at'],
                'unique_together': {('user', 'test_type')},
            },
        ),
    ]
