# Generated by Django 5.2.7 on 2026-08-13 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='document_type',
            field=models.CharField(choices=[('certificate', 'Сертификат'), ('diploma', 'Диплом')], default='certificate', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testresult'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='test_type',
            field=models.CharField(choices=[('junior', 'Младшая группа'), ('teen', 'Подростковая группа'), ('adult', 'Взрослые')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'test_type', 'document_type')},
        ),
    ]
